### ISSUE TITLE
slurm uid and gid must be consistent across the cluster

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-slurm#11]
In our cluster slurmctld run on a node where the user "slurm" happens to have uid 994. On another node recently installed the slurm user happened to get uid=995, gid=992. As a result, slurmd refuses to talk to slurmctld, in the log we see:

Feb 11 13:03:05 pe4 slurmd[22276]: error: Security violation, acct_gather_update RPC from uid 994
Feb 11 13:03:05 pe4 slurmd[22276]: error: Do you have SlurmUser configured as uid 994?

Thus, the role must create a slurm user and group with consistent ID's on the entire cluster.

**Comment by A1ve5** [comment]
Would this do it?
https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/commit/f2769baf2927f4ce26b4a437402731c931632515

**Comment by jabl** [comment]
I think it would be nicer if the slurm user and group would have the same uid/gid, hence what I proposed in my pull request. Though I'm not sure if it makes any actual difference.

**Comment by A1ve5** [comment]
Just made the defaults to fit what we have in Io. You can always overwrite the defaults by putting the same variables in group_vars/all/all.yml

**Comment by A1ve5** [comment]
made kind of a mix here https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/commit/fbcfc086667e91a556e4e79a44e942b8ef7e1dd6

**Comment by jabl** [comment]
Fine by me. From our perspective, since we must redo it anyway as most nodes seem to have them inconsistent, we might as well do it "correctly" then.

**Comment by jabl** [comment]
Another bug:

$ id slurm
uid=681(slurm) gid=100(users) groups=100(users)

group is incorrect.

**Comment by tiggi** [comment]
On 2016-02-12 10:35, Janne Blomqvist wrote:
> Another bug:
>
> $ id slurm
> uid=681(slurm) gid=100(users) groups=100(users)
>
> group is incorrect.
>


You are doing this wrong.

The slurm user + group should be added via ldap/nis _once_ and not at 
all to each compute node.

Usermapping is done centrally just for this reason.

If the install-node is down, slurm won't work anyway.




-- 
Ulf Tigerstedt || Senior systems specialist
CSC Oy || NeIC NT1 / NDGF GSM +358503818558
Johannesbergsvägen 17 || Närpes || Finland

**Comment by jabl** [comment]
Yeah, that's probably a better solution. Then the playbook should be changed so that it doesn't try to create a local user on all the compute nodes. 

And if we do this, I guess we can just get rid of these slurm_uid and slurm_gid parameters, and just let useradd/groupadd on the install node allocate an available ID. One less thing to go wrong..

**Comment by tiggi** [comment]
On 2016-02-12 10:49, Janne Blomqvist wrote:
> Yeah, that's probably a better solution. Then the playbook should be
> changed so that it doesn't try to create a local user on all the compute
> nodes.
>
> And if we do this, I guess we can just get rid of these slurm_uid and
> slurm_gid parameters, and just let useradd/groupadd on the install node
> allocate an available ID. One less thing to go wrong..


FGI clusters only has slurm mapped on the install node, nowhere else.



-- 
Ulf Tigerstedt || Senior systems specialist
CSC Oy || NeIC NT1 / NDGF GSM +358503818558
Johannesbergsvägen 17 || Närpes || Finland

**Comment by jabl** [comment]
Ok, https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/pull/14 now tries to make sure we create the slurm user/group only on the NIS server.

**Comment by A1ve5** [comment]
Should have tested it before. Changing user's home while the user is running anything will break the playbook. I propose not setting any home dir.

**Comment by A1ve5** [comment]
-    user: name=slurm shell=/sbin/nologin createhome=no home=/ system=yes append=yes group=slurm
+    user: name=slurm shell=/sbin/nologin createhome=no system=yes append=yes group=slurm state=present

**Comment by jabl** [comment]
Gah, still doesn't work. Now the problem is that we're creating the slurm usr/group as a system user/group (which is correct per se), however, NIS doesn't add system users/groups to the maps (see MINUID etc. in /var/yp/Makefile), which is also sensible.

**Comment by A1ve5** [comment]
What about dropping the system user/group setting?

**Comment by avatar-lavventura** [comment]
Both my frontEnd and compute node has the same UID and GID but I am having same error. How can I fix this problem?

My frontEnd:
`uid=1000(alper) gid=1003(alper) groups=1003(alper),27(sudo),999(docker)`

My compute node:
`uid=1000(alper) gid=1003(alper) groups=1003(alper_alimoglu),4(adm),30(dip),44(video),46(plugdev),1000(google-sudoers)`

Error message:

```
slurmd: debug2: got this type of message 4005
slurmd: debug2: Processing RPC: REQUEST_BATCH_JOB_LAUNCH
slurmd: error: Security violation, batch launch RPC from uid 1000
slurmd: debug3: in the service_connection
slurmd: debug2: got this type of message 6011
slurmd: debug2: Processing RPC: REQUEST_TERMINATE_JOB
slurmd: debug:  _rpc_terminate_job, uid = 1000
slurmd: error: Security violation: kill_job(26) from uid 1000
slurmd: debug3: in the service_connection
slurmd: debug3: in the service_connection
slurmd: debug2: got this type of message 6011
slurmd: debug2: Processing RPC: REQUEST_TERMINATE_JOB
slurmd: debug:  _rpc_terminate_job, uid = 1000
slurmd: error: Security violation: kill_job(24) from uid 1000
slurmd: debug2: got this type of message 6011
slurmd: debug2: Processing RPC: REQUEST_TERMINATE_JOB
slurmd: debug:  _rpc_terminate_job, uid = 1000
slurmd: error: Security violation: kill_job(25) from uid 1000
^Cslurmd: got shutdown request
slurmd: all threads complete
slurmd: Munge cryptographic signature plugin unloaded
slurmd: Slurmd shutdown completing
```

**Comment by avatar-lavventura** [comment]
I have asked to slurm mailling list, please [see](https://groups.google.com/forum/#!topic/slurm-users/0kEkqYHDpp4), no-one responded yet.  @martbhell 

No I am not using `ansible-role-slurm`. I have builded both frontEnd and compute node as follows, could it be the reason where I also build compute node with `--enable-front-end` flag?:

```
git clone https://github.com/SchedMD/slurm
cd slurm
./configure --enable-debug --enable-front-end
sudo make install
```

**Comment by martbhell** [comment]
OK I don't know what that compilation flag does (nor could I figure it out from grepping configure file) and I haven't used it.
I've used "rpmbuild -ta slurm-17.11.5.tar.bz2 --with lua --with mysql"

**Comment by avatar-lavventura** [comment]
at Controller:

```
$ scontrol -V
slurm 17.02.0-0pre1
alper@ebloc:~$ sacctmgr show user
      User   Def Acct     Admin
---------- ---------- ---------
     alper      alper      None
    deneme     deneme      None
    netlab     netlab      None
      root       root Administ+
alper@ebloc:~$ sbatch --uid=alper hostname
sbatch: error: This does not look like a batch script.  The first
sbatch: error: line must start with #! followed by the path to an interpreter.
sbatch: error: For instance: #!/bin/sh
```

At Compute node:

```
$  scontrol -V
slurm 17.02.0-0pre1
$ sacctmgr show user
      User   Def Acct     Admin 
---------- ---------- --------- 
alper_ali+ alper_ali+      None 
      root       root Administ+
$ sbatch --uid=alper hostname
sbatch: error: This does not look like a batch script.  The first
sbatch: error: line must start with #! followed by the path to an interpreter.
sbatch: error: For instance: #!/bin/sh
```

**Comment by A1ve5** [comment]
Sorry, my bad, that should be a bash script.

Try putting something like this in a script file and submit it with sbatch:
#!/bin/sh
hostname

Anyway, quick question, what do you have as SlurmUser in the slurm.conf
configuration file? is the daemon running as that user and does it have
access to the needed folders?
Have a look at https://slurm.schedmd.com/quickstart_admin.html under
"Configuration" section.

**Comment by A1ve5** [comment]
One thing that I've noticed, I cannot recall if that's normal or not, why sacctmgr User is "alper" in the controler and "alper_ali+" in the compute? Does that make a difference.

@avatar-lavventura I'm sorry but what I can provide now are merely guesses since I don't have a Slurm system available and my memory on Slurm isn't helping much.

**Comment by avatar-lavventura** [comment]
Should both controller and compute node have the same user name? I will try both having `alper` and see does this make any help.
