### ISSUE TITLE
Create slurm group & user before installing slurn

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#13]
So we don't change it or leave some residue on the system.

**Comment by A1ve5** [comment]
Seems to be addressed here: f227c52f8683e4a35596b2bcede4e824d62a428d

**Comment by martbhell** [comment]
I don't see it in common.yml in master

**Comment by A1ve5** [comment]
It's there but not in the right orther

**Comment by A1ve5** [comment]
changed the user and group creation from common to service

**Comment by martbhell** [comment]
okay. slurm will still install on a compute and submit node if the central user database is not working. We could add an assert: into their task files to make sure that there is a slurm user available.
