### ISSUE TITLE
Enable pam_slurm.so

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-slurm#17]
pam_slurm.so (from the slurm-pam_slurm rpm package) should be enabled in PAM configuration. It prevents local users from accessing nodes where they don't have jobs running.

**Comment by martbhell** [comment]
Bonus feature related to this: in commit https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/commit/93af9538fa194182f095476449d64b7a65f97cf1 we allow users from the slurm_sshd_access_groups list to SSH in by pam_access.so
