### ISSUE TITLE
slurmctld isn't enabled by the role

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#19]

**Comment by martbhell** [comment]
More details and research needed.
It would be nice if the role would still work on EL6 / init.d systems.

systemd on EL7 have both the /etc/init.d/slurm service as well as the slurmctld, slurmdbd and slurmd.services scripts.

**Comment by jabl** [comment]
FWIW, I think it's a bug in the rpm spec that the init.d script is included in the EL7 rpms. So we should ignore it, and use the systemd services.

**Comment by martbhell** [comment]
slurmctld is enabled since a2333d9cf63e2e7c6bf7df5f3fb14c1d1e8e1859
