### ISSUE TITLE
error: _cpu_freq_cpu_avail: Could not open 

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#2]
On node logs:

io1.fgci.csc.fi slurmd[23484]: error: _cpu_freq_cpu_avail: Could not open /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies

**Comment by martbhell** [comment]
Changed name. The playbook runs fine now. But these errors about scaling_available_frequencies are still in the logs.

**Comment by martbhell** [comment]
http://unix.stackexchange.com/questions/153693/cant-use-userspace-cpufreq-governor-and-set-cpu-frequency maybe this is related.

**Comment by martbhell** [comment]
It might be good to change the power setting to dynamic. Setting it to high performance likely hides all the power settings from the operating system.

**Comment by martbhell** [comment]
Setting the system power profile to PerfOptimized or PerfPerWattOptimizedOs makes no difference - slurm still gives this error and one can in both cases one can use "tuned-adm" to set various profiles and the cpuspeed changes.
Marking this as won't solve.

**Comment by jabl** [comment]
FWIW, I fixed this in 16.05: https://github.com/SchedMD/slurm/commit/a4f35c45eddf54d9305e5a16352dabdab3ad97b3
