### ISSUE TITLE
Use common queue names

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-slurm#22]
From https://hpcbios.readthedocs.org/en/latest/HPCBIOS_05-05.html

**Comment by martbhell** [comment]
I guess we need to keep the grid queue.

Been thinking of adding a for loop to the slurm.conf.j2 to add partitions from a list of dicts. 
Maybe now would be a good time to implement that.

**Comment by jabl** [comment]
I've been thinking of the same. Also for nodes, since we have heterogeneous nodes so we need several NodeName=... lines in slurm.conf.

If one doesn't want to break sites running with the current out-of-the-box setup, one could do something like

{% if slurm_nodelist is defined %}
Loop over a list of maps, each of which generates one "NodeName=" line in the conf file.
{% else %}
Use the current variables
{% endif %}

?

**Comment by martbhell** [comment]
Yes. Shall we add all partition settings with | default('value') }} too?  or should it just be a dictionary of nodes and one argument with all partition settings a site wants to set?

**Comment by jabl** [comment]
Hmm, maybe there's no particular value in specifying all kinds of parameters as separate keys, just put everything in a string? E.g. some YAML like

slurm_nodelist:
    - "NodeName=pe[1-1234]  RealMemory=NNN Feature=haswell"
    - "NodeName=ivy[1-48] RealMemory=MMM Feature=ivybridge"
    - "NodeName=gpu[23-25] Gres=gpu:4 Feature=haswell,teslak80"
    - etc...

and similar for partition configs? That would be the easiest, at least. 

I don't think we need to worry about defaults, since if slurm_nodelist isn't defined the site just get the current defaults anyway?

**Comment by martbhell** [comment]
Agreed. Is also less maintenance needed on the role to support newer slurms. I'll have a look at this tomorrow.
