### ISSUE TITLE
upload a pre made slurm.conf file

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#24]
Make it possible to simply upload a pre made slurm.conf file

**Comment by A1ve5** [comment]
If there a slurm.conf file in fgci-ansible/files upload it and bypass it's build from variables.
Maybe, if exists just overwrite file.

**Comment by martbhell** [comment]
Where would ansible-pull copy the slurm.conf from?

**Comment by A1ve5** [comment]
from install node

**Comment by A1ve5** [comment]
not needed anymore
