### ISSUE TITLE
Support for topology plugin

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-slurm#32]
Would be nice if we could support the topology plugin. In particular, the tree plugin.

**Comment by martbhell** [comment]
Added possibility to configure a topology plugin.

Theoretically it'd be quite cool to use build this from hostvar hostname.interfacename.macaddress  and query the switch API (if they have one).

But more realistically how about we just populate topology.conf with templates from a dictionary, from something like this?

slurm_topology_tree:
 - { switch: "switch1", nodes: "pe[1-16]" }
 - { switch: "switch2", nodes: "pe[17-32]" }

**Comment by jabl** [comment]
Well, the topology we're interested in is the IB topology. That is, the point is to allow the scheduler to pack parallel jobs on as few switches as possible.

It's not that hard to automate it actually, I have an old tool for generating a graphviz file from the topology created by 'ibnetdiscover' at https://github.com/jabl/ibtopo2dot , one could start from that..

But yeah, in reality it's certainly good enough to specify the topology manually. That actually allows some useful extra "features". E.g. if you create a disconnected topology slurm will never schedule a job across a set of nodes that are not connected.  This can be useful e.g. if your IB net is heavily oversubscribed, and you don't want MPI traffic over your spine switches.

**Comment by jabl** [comment]
Pull request to generate topology.conf, similarly to gres.conf: https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/pull/62

**Comment by jabl** [comment]
https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/pull/62 is merged, closing
