### ISSUE TITLE
Missing %

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#35]
https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/blob/master/templates/slurm.conf.j2#L15

**Comment by jabl** [comment]
Sorry about this!

Could you tag this version and update requirements.yml in fgci-ansible too?

**Comment by A1ve5** [comment]
Oh, yes, forgot about this.
Sami Maisala reported that there's another missing % on line 45.
https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/blob/50b1d2b69d230dffec2ee49fe42252397988dabb/templates/slurm.conf.j2#L45

**Comment by jabl** [comment]
Ah, dang. Those templates are so hard to get right! :(

**Comment by A1ve5** [comment]
Done. Requirements.yml should be ok now

**Comment by martbhell** [comment]
Got some more travis CI testing working in #5 - hopefully this will catch errors in the future. Not sure if it will barf on the missing % though.
