### ISSUE TITLE
check if cluster is created before adding it 

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#4]
sacctmgr complains if one tries to add a cluster that already exists.

https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm/blob/master/tasks/service.yml#L183

**Comment by A1ve5** [comment]
failed: [io-install.fgci.csc.fi] => {"changed": true, "cmd": ["sacctmgr", "-i", "add", "cluster", "io"], "delta": "0:00:00.166378", "end": "2015-11-24 10:09:55.587566", "rc": 1, "start": "2015-11-24 10:09:55.421188", "warnings": []}
stdout:  This cluster io already exists.  Not adding.
