### ISSUE TITLE
logrotate.d/slurm missing

### ISSUE THREAD

**Issue by dgtim** [CSC-IT-Center-for-Science/ansible-role-slurm#42]
/var/log/slurm/*.log files are growing huge. Especially on install where SLURM controller is run.

/etc/logrotate.d/slumr could be something like, on all the nodes that run SLURM.

/var/log/slurm/*.log {
    weekly
    missingok
    notifempty
    sharedscripts
    rotate 8
    compress
    postrotate
        /bin/kill -HUP `cat /var/run/slurm/slurmctld.pid  2>/dev/null`  2> /dev/null || true
        /bin/kill -HUP `cat /var/run/slurm/slurmdbd.pid  2>/dev/null`  2> /dev/null || true
    endscript
}

**Comment by dgtim** [comment]
The above example will work if SLURM has all the Log vars defined, like

JobCompLoc              = /var/log/slurm_jobcomp.log
SlurmctldLogFile        = /var/log/slurm/slurmctld.log
SlurmdLogFile           = /var/log/slurm/slurmd.log

Seems that default on FGCI is using syslog for others except slurm_jobcomp.log, then

/var/log/slurm/*.log {
    weekly
    missingok
    notifempty
    sharedscripts
    rotate 8
    compress
    create 644 slurm slurm
    postrotate
        /bin/kill -HUP `cat /var/run/slurmctld.pid  2>/dev/null`  2> /dev/null || true
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        /bin/kill -HUP `cat /var/run/slurmdbd.pid  2>/dev/null`  2> /dev/null || true
    endscript
}

**Comment by dgtim** [comment]
The aobve one has been tested on Triton's install2, though should work on all other nodes as well including admin2 that runs slurmdbd.

**Comment by martbhell** [comment]
Thanks @dgtim I added this to the slurm role. I'd like to confirm that logrotates are working with this configuration so putting this task in review - running "logrotate /etc/logrotate.conf" interactively does not rotate them on our test system. Maybe I have to wait a week..

**Comment by martbhell** [comment]
Files were rotated on our test system Sunday morning.
