### ISSUE TITLE
Make all settings in slurm.conf.j2 variables

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#43]
There are a few variables remaining in slurm.conf.j2 we could allow to be changed with variables.

For example all the ones under "TIMERS" section and some ports for services.

**Comment by martbhell** [comment]
A branch or PR would have been good here. Quite safe for us as we don't use the master branch though.

If you comment out setting the variables you cannot use them in the template (well, the ansible task will fail) without first checking if they are defined.

**Comment by A1ve5** [comment]
All the commented in defaults are the ones commented in the template so it shouldn't fail.
