### ISSUE TITLE
Logrotate isn't working for /var/log/slurm/slurm_jobcomp.log

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#51]
After log rotation slurm stops writing on slurm_jobcomp.log
This seems to be because slurm service need a restart in order to release the log file.

Proposal:

Start writing slurm_jobcomp.log in /home/admin NFS share and whenever we run the backup playbook (to be release soon), this stops slurm for a DB dump which give us the opportunity to compress slurm_jobcomp.log and keep the "house" cleaner.

This issue is somehow related to Issue #42

**Comment by martbhell** [comment]
Related to #52
