### ISSUE TITLE
Add Slurm fairshare commands for 20/80 FGCI rule

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-slurm#61]
[root@io-install ~]# sacctmgr modify account name=local set fairshare=80000
 Modified account associations...
  C = io         A = local of root
Would you like to commit changes? (You have 30 seconds to decide)
(N/y): y

20% for fgi:

[root@io-install ~]# sacctmgr modify account name=fgi set fairshare=20000
 Modified account associations...
  C = io         A = fgi of root
Would you like to commit changes? (You have 30 seconds to decide)
(N/y): y

and 100% (which effectively is ~0% due to the shortness of monitoring jobs, more info bellow):

[root@io-install ~]# sacctmgr modify account name=ops set fairshare=100000
 Modified account associations...
  C = io         A = ops of root
Would you like to commit changes? (You have 30 seconds to decide)
(N/y): y

**Comment by martbhell** [comment]
For fgci I think this fits better in arc-frontend where we also create the accounts already. 
But it would be cool if this role also supported setting up slurm accounting stuff.

**Comment by A1ve5** [comment]
doing it on arc-frontend.

**Comment by A1ve5** [comment]
here: https://github.com/CSC-IT-Center-for-Science/ansible-role-arc-frontend/commit/202a5558eb8088be15eaa83201be1116b5ed6ddc

Closing
