### ISSUE TITLE
Add handler for restarting rsyslogd when rsyslog config changes

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-slurm#65]

**Comment by martbhell** [comment]
Tried adding a handler, but that didn't work in the docker image because they don't have rsyslog installed. Instead made the templating of the rsyslog.conf optional in 5c69640566402978c0586a9b7d792f827b487622 

 - Is this enough or 
 - Shall we assume rsyslog is installed (or even install it with this role) - is there currently a reasonable usecase where one could run slurm on a system where rsyslog isn't installed?

**Comment by jabl** [comment]
Can't you assume that rsyslog is installed if slurm_manage_rsyslog_conf is True, and notify the handler then?

I don't think this role should install rsyslog, as there's of course a lot of other non-slurm related things you have to take care when properly installing and configuring rsyslog.

It is possible to configure slurm to log to local files, but then you're, well, stuck with a bunch of log files spread out over all the nodes in your cluster. So you'll have to figure out a way to ship them to wherever you want, and the parse the custom format. So I'd argue the only sane way to run slurm is to log via syslog.

**Comment by martbhell** [comment]
Yeah we can. I'll add an exception to the test to install rsyslog before this role

**Comment by martbhell** [comment]
Merged in #71
