### ISSUE TITLE
16.05 Upgrade: libslurm.so.29 -> .30 symlinks 

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-slurm#69]
It seems we have to do symlinks from libslurm.so.29 to libslurm.so.30 when upgrading from 15.08 to 16.05. I've been trying to compile OpenMPI such that I get rid of the dependency on libslurm.so, to no avail. 

Symlinking like this is of course a bit dangerous, but if you use the PMI interface instead of the old pre-PMI direct slurm interface, one shouldn't need to actually use anything from libslurm.so from openMPI, so the symlinks are just there to satisfy the dynamic linker.

Or might it be better to create these symlinks manually (with pdsh, say) and then remove them again as soon as OpenMPI modules have been rebuilt?

**Comment by jabl** [comment]
@A1ve5 what do you think?

**Comment by A1ve5** [comment]
@jabl I'll test th emanual option in Io

**Comment by A1ve5** [comment]
From my tests,
ln -s /usr/lib64/libslurm.so.30.0.0 /usr/lib64/libslurm.so.29.0.0 && ln -s /usr/lib64/libslurm.so.30 /usr/lib64/libslurm.so.29

seems to be working for now

**Comment by martbhell** [comment]
If we are to do this with the ansible-role-slurm we should have a generic way of determining when the symlinks needs to be in place. If we were to push this change into the role, odds are anyway that it wouldn't affect all the FGCI sites as all aren't religiously updating (which is fine).

I propose we either do it manually or by adding the symlinks to one of the RPMs installed like slurm-fgi-addons or fgci-meta-compute - that way they would get installed on all the clusters with auto-update enabled.
